trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

 - script: rm -r TypeAuthTests; rm -r TypeAuth.Shared; rm -r TypeAuth.Docs; rm -r TypeAuth.AspNetCore.Tests; rm -r TypeAuth.AspNetCore.Sample
   displayName: 'remove unused projects'

 - script: dotnet build --configuration release
   displayName: 'dotnet build'

 - script: dotnet pack TypeAuth.Core --configuration release --output $(Build.ArtifactStagingDirectory)
   displayName: 'dotnet pack'

 - task: NuGetCommand@2
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'