trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

 - script: dotnet build TypeAuth.Core --configuration release
   displayName: 'dotnet build TypeAuth.Core'

 - script: dotnet build TypeAuth.AspNetCore --configuration release
   displayName: 'dotnet build TypeAuth.AspNetCore'

 - script: dotnet pack TypeAuth.AspNetCore --configuration release --output $(Build.ArtifactStagingDirectory)
   displayName: 'dotnet pack'

 - task: NuGetCommand@2
   condition: contains(variables['Build.SourceBranch'], 'refs/tags/release') 
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'